// Generated by HSL Sound Design Agent - AudioPlan v1.0.0
// Video ID: BRECHA_EPISODE_003 | Total Frames: 1800 | FPS: 30
import React from 'react';
import {Audio, Sequence, staticFile, interpolate} from 'remotion';

function dbToLinear(db: number): number {
  return Math.pow(10, db / 20);
}

export const RemotionCinematicAudioBed: React.FC = () => {
  return (
    <>
      {/* ======================================================== */}
      {/* SCENE: scene_001 (suspense | industrial_technical_facility) */}
      {/* ======================================================== */}
      <Sequence from={0} durationInFrames={110}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={90}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1778}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={110}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (whoosh | whoosh_transition | high) */} 
        <Sequence from={65} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_001 (triple_calcar) */}
        <Sequence from={90} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={85} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={110} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_002 (suspense | aqueduct_pumping_station) */}
      {/* ======================================================== */}
      <Sequence from={110} durationInFrames={437}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={437}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_002 (triple_calcar) */}
        <Sequence from={417} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={412} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={437} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_003 (suspense | aqueduct_pumping_station) */}
      {/* ======================================================== */}
      <Sequence from={547} durationInFrames={100}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={100}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (whoosh | whoosh_transition | high) */} 
        <Sequence from={55} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_003 (triple_calcar) */}
        <Sequence from={80} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={75} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={100} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_004 (suspense | aqueduct_pumping_station) */}
      {/* ======================================================== */}
      <Sequence from={647} durationInFrames={255}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={255}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_004 (triple_calcar) */}
        <Sequence from={235} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={230} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={255} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_005 (suspense | industrial_technical_facility) */}
      {/* ======================================================== */}
      <Sequence from={902} durationInFrames={110}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={110}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (whoosh | whoosh_transition | high) */} 
        <Sequence from={65} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_005 (triple_calcar) */}
        <Sequence from={90} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={85} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={110} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_006 (dark | industrial_technical_facility) */}
      {/* ======================================================== */}
      <Sequence from={1012} durationInFrames={437}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={437}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (whoosh | whoosh_transition | high) */} 
        <Sequence from={392} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_007 (impact | ominous_boom | low) */} 
        <Sequence from={240} durationInFrames={50}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_006 (triple_calcar) */}
        <Sequence from={417} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={412} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={437} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_007 (suspense | industrial_technical_facility) */}
      {/* ======================================================== */}
      <Sequence from={1449} durationInFrames={100}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={100}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (foley | valve_turn | mid) */} 
        <Sequence from={15} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_007 (whoosh | whoosh_transition | high) */} 
        <Sequence from={55} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_007 (triple_calcar) */}
        <Sequence from={80} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={75} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={100} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_008 (suspense | aqueduct_pumping_station) */}
      {/* ======================================================== */}
      <Sequence from={1549} durationInFrames={251}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_orchestra_01.wav')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={251}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (foley | valve_turn | mid) */} 
        <Sequence from={15} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')}
            volume={0.0794}
          />
        </Sequence>
      </Sequence>

    </>
  );
};
