import fs from 'node:fs'; import path from 'node:path'; import {interrupt,Send} from '@langchain/langgraph';
import {Context,NodeFn,paths,writeJson,copyFile} from '../runtime'; import {agentGuide,planTakes} from '../lib/firefly'; import type {VideoTake,AssetResult} from '../state';
export const fireflySessionPrepare=(c:Context):NodeFn=>async s=>{if(s.options.graph.mediaMode==='legacy')return{__status:'skipped'};const e=c.deps.fireflyEnvironment();const runtime=path.join(paths(c,s).run,'firefly','session');const log=path.join(paths(c,s).audit,'firefly-session.log');const valid=await c.deps.probeFireflySession(e,runtime,log);if(!valid)await c.deps.openFireflyLogin(e,log);return{environment:{agentDir:e.agentDir,profileDir:e.profileDir,sessionValid:valid}};};
export const fireflySessionWait:NodeFn=s=>{if(s.options.graph.mediaMode==='legacy'||s.environment?.sessionValid)return{__status:'skipped'};interrupt({kind:'FIREFLY_LOGIN',profileDir:s.environment?.profileDir});return{};};
const key=(t:VideoTake)=>`${t.beatId}-take-${t.takeIndex}`;
function reusable(c:Context,t:VideoTake){try{if(!fs.existsSync(t.outputPath))return false;const p=c.deps.inspect(t.outputPath);return p.hasVideo&&p.codecName==='h264'&&p.width===1920&&p.height===1080&&p.durationSeconds>=4.5;}catch{return false;}}
export const fireflyGuide=(c:Context):NodeFn=>s=>{if(s.options.graph.mediaMode==='legacy')return{__status:'skipped'};const dir=path.join(paths(c,s).run,'firefly','takes');const images=new Map(s.frames.map(f=>[f.beatId,f.path]));const videoIds=new Set(s.scenePlan!.beats.filter(b=>b.visualMode==='firefly_video').map(b=>b.beatId));const prompts=s.visualPrompts.filter(p=>videoIds.has(p.beatId));const takes=planTakes(prompts,images,dir);const reusableTakes=takes.filter(t=>reusable(c,t)).length;const requiredGenerations=takes.length-reusableTakes;const guidePath=path.join(paths(c,s).run,'firefly','guide.json');writeJson(guidePath,{model:'Kling 2.5 Turbo',takeSeconds:5,splitOver:5.5,videoBeats:prompts.length,totalTakes:takes.length,reusableTakes,requiredGenerations,takes});const budget={kind:'KLING_BUDGET',model:'Kling 2.5 Turbo',videoBeats:prompts.length,totalTakes:takes.length,reusableTakes,requiredGenerations,message:`Autorizar exatamente ${requiredGenerations} novas gerações Kling?`};if(requiredGenerations===0)return{videoTakes:takes,fireflyGuidePath:guidePath,__status:'skipped'};if(s.options.graph.maxGenerations>=requiredGenerations)return{videoTakes:takes,fireflyGuidePath:guidePath,gateDecisions:[{gate:'kling',decision:'proceed',at:new Date().toISOString()}]};const answer=interrupt(budget) as {decision?:string};if(answer?.decision==='abort')return{videoTakes:takes,fireflyGuidePath:guidePath,gateDecisions:[{gate:'kling',decision:'abort',at:new Date().toISOString()}],productionStatus:'ABORTED'};if(answer?.decision!=='proceed')throw new Error('KLING_BUDGET_DECISION_INVALID');if(s.options.graph.maxGenerations<requiredGenerations)throw new Error(`KLING_BUDGET_LIMIT_TOO_LOW:required=${requiredGenerations}:limit=${s.options.graph.maxGenerations}`);return{videoTakes:takes,fireflyGuidePath:guidePath,gateDecisions:[{gate:'kling',decision:'proceed',at:new Date().toISOString()}]};};
export const routeKlingBudget=(s:any)=>s.productionStatus==='ABORTED'?'finalize':'firefly_dispatch';
export const fireflyDispatch=(c:Context):NodeFn=>async s=>{if(s.options.graph.mediaMode==='legacy')return{__status:'skipped'};const takes=s.videoTakes.map(t=>({...t}));const next=takes.find(t=>!['ok','skipped'].includes(t.status));if(!next)return{__status:'skipped'};if(next.dependsOnTake&&!takes.some(t=>key(t)===next.dependsOnTake&&['ok','skipped'].includes(t.status)))throw new Error(`FIREFLY_DEPENDENCY_PENDING:${next.dependsOnTake}`);
 if(reusable(c,next)){const p=c.deps.inspect(next.outputPath);next.status='skipped';next.actualSeconds=p.durationSeconds;const following=takes.find(x=>x.dependsOnTake===key(next));if(following&&!fs.existsSync(following.firstFramePath))await c.deps.extractLastFrame(next.outputPath,following.firstFramePath);return{videoTakes:takes};}
 const counted=takes.filter(t=>t.generationCounted).length;if(counted+1>s.options.graph.maxGenerations)throw new Error(`MAX_GENERATIONS_EXCEEDED:required=${counted+1}:limit=${s.options.graph.maxGenerations}:next=${key(next)}`);
 const prompt=s.visualPrompts.find(p=>p.beatId===next.beatId)!;const runtime=path.join(paths(c,s).run,'firefly','runtime',key(next));const guide=path.join(runtime,'guide.json');writeJson(guide,agentGuide(prompt,next));next.startedAt=new Date().toISOString();next.generationCounted=true;next.status='dispatched';
 try{await c.deps.runFireflyTake(c.deps.fireflyEnvironment(),runtime,guide,path.join(paths(c,s).audit,`${key(next)}.log`));}
 catch(e){interrupt({kind:'FIREFLY_RECOVERY',take:key(next),reason:e instanceof Error?e.message:String(e),receiptPath:path.join(runtime,'dispatch-receipt.json'),retryPolicy:'manual-reconcile-no-auto-resubmit'});return{};}
 const produced=path.join(runtime,'saida',`${key(next)}.mp4`);if(fs.existsSync(produced))copyFile(produced,next.outputPath);return{videoTakes:takes,generationCount:counted+1};};
export const fireflyIntakeWait=(c:Context):NodeFn=>async s=>{if(s.options.graph.mediaMode==='legacy')return{__status:'skipped'};const takes=s.videoTakes.map(t=>({...t}));const t=takes.find(x=>x.status==='dispatched');if(!t)return{};let probe:any;try{probe=await c.deps.detailedProbe(t.outputPath);if(probe.codec!=='h264'||!probe.width||!probe.height||Math.abs(probe.width/probe.height-16/9)/(16/9)>0.01||probe.duration<t.requestedSeconds-.5)throw new Error(`probe incompatível ${JSON.stringify(probe)}`);}catch(e){interrupt({kind:'FIREFLY_RECOVERY',missing:[{take:key(t),expectedPath:t.outputPath,reason:e instanceof Error?e.message:String(e)}],outputDir:path.dirname(t.outputPath)});return{};}t.status='ok';t.actualSeconds=probe.duration;t.endedAt=new Date().toISOString();const following=takes.find(x=>x.dependsOnTake===key(t));if(following)await c.deps.extractLastFrame(t.outputPath,following.firstFramePath);return{videoTakes:takes};};
export const routeTakes=(s:any)=>s.videoTakes.every((t:any)=>['ok','skipped'].includes(t.status))?'firefly_finalize':[new Send('firefly_dispatch',s)];
export const fireflyFinalize=(c:Context):NodeFn=>async s=>{if(s.options.graph.mediaMode==='legacy')return{__status:'skipped'};const videos:AssetResult[]=[];const videoIds=new Set(s.scenePlan!.beats.filter(b=>b.visualMode==='firefly_video').map(b=>b.beatId));for(const p of s.visualPrompts.filter(p=>videoIds.has(p.beatId))){const takes=s.videoTakes.filter(t=>t.beatId===p.beatId).sort((a,b)=>a.takeIndex-b.takeIndex);const out=path.join(paths(c,s).run,'videos',`${p.beatId}.mp4`);if(takes.length===1)copyFile(takes[0].outputPath,out);else await c.deps.concatTakes(takes.map(t=>t.outputPath),out);const pub=path.join(c.root,'public','runs',s.episodeId,'videos',`${p.beatId}.mp4`);copyFile(out,pub);videos.push({beatId:p.beatId,path:out,status:takes.every(t=>t.status==='skipped')?'skipped':'ok',attempts:1});}return{videos};};
