import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {Command} from '@langchain/langgraph'; import {createCheckpointer} from '../../checkpointer'; import {createProductionGraph} from '../graph';
import {executeProduction} from '../runner'; import {initialState} from '../state'; import {fixtures,media} from './fixtures'; import {takeCount,planTakes} from '../lib/firefly/guide';

const base=fs.mkdtempSync(path.join(os.tmpdir(),'hsl-phase2-'));
function prompts(plan:any){return {beats:plan.beats.map((b:any)=>({beatId:b.beatId,imagePrompt:`Photorealistic cinematic industrial documentary scene for ${b.beatId}, no text or logos`,videoPrompt:`Slow controlled documentary camera motion through the physical system for ${b.beatId}`,cameraMotion:b.cameraMovement,durationSeconds:b.durationSeconds,firstFrameFrom:'image'}))};}
function setup(name:string,opts:{missingTake?:number;lowReview?:boolean;sessionInvalid?:boolean;unresolved?:boolean;busy?:boolean}={}){const root=path.join(base,name);fs.mkdirSync(root,{recursive:true});const f=fixtures(root,name);let ideCalls=0,runCalls=0,probeCalls=0;const plan=f.deps.plan!({} as any);const selected={...plan,beats:plan.beats.slice(0,2)};for(const b of selected.beats)media(path.join(root,'runs',name,'images',b.beatId,`${b.beatId}.png`),true);
 const deps:any={...f.deps,fireflyEnvironment:()=>({agentDir:root,profileDir:path.join(root,'profile'),python:'python'}),profileInUse:async()=>false,
  probeFireflySession:async()=>{probeCalls++;return opts.sessionInvalid?probeCalls>1:true;},openFireflyLogin:async()=>({exitCode:0,stdout:'',stderr:'',timedOut:false,durationMs:1}),
  ide:async(task:any)=>{ideCalls++;const output=task.node==='visual-prompts-review'?{score:opts.lowReview&&ideCalls<3?40:95,issues:opts.lowReview&&ideCalls<3?[{beatId:selected.beats[0].beatId,message:'more concrete'}]:[]}:prompts(selected);return {prepared:{} as any,headlessResult:{provider:task.provider,ok:true,outputPath:'mock',durationMs:1,output}};},
  runFireflyTake:async(_e:any,runtime:string,guidePath:string)=>{if(opts.busy)throw new Error('FIREFLY_PROFILE_IN_USE:D:\HSL-FIREFLY-PROFILE');runCalls++;const g=JSON.parse(fs.readFileSync(guidePath,'utf8'));if(runCalls!==opts.missingTake){media(path.join(runtime,'saida',g.items[0].name+'.mp4'),false,5);}return {feed:{exitCode:0},run:{exitCode:0}};},
  detailedProbe:async(file:string)=>{const p=JSON.parse(fs.readFileSync(file,'utf8').slice(0,fs.readFileSync(file,'utf8').indexOf('}')+1));return {duration:p.durationSeconds,width:p.width,height:p.height,codec:p.codecName,fps:24};},
  extractLastFrame:async(_v:string,out:string)=>media(out,true),concatTakes:async(_takes:string[],out:string)=>{media(out,false,10);return{reencoded:[]};},
  renderSfx:async(_r:string,_p:string,out:string)=>{media(out,false,12);return{resolved:[{id:'one',description:'impact',offsetSeconds:0,targetDb:-15,sourcePath:'kenney'}],unresolved:opts.unresolved?[{id:'x',description:'drone',offsetSeconds:0,targetDb:-28,reason:'unresolved'}]:[]};},
  renderChunk:async(r:string,e:string)=>{media(path.join(r,'out','test',`.visual-${e}-2beats.mp4`));return{exitCode:0,stdout:'',stderr:'',timedOut:false,durationMs:1};},
  muxFinalWithSfx:async(_v:string,_m:string,_n:string,_s:string,out:string)=>media(out),
 };
 const saver=createCheckpointer(root),graph=createProductionGraph(saver,deps,root,{interruptAfter:['mux']});return{root,saver,graph,deps,get runCalls(){return runCalls},get ideCalls(){return ideCalls}};}
async function runNew(x:ReturnType<typeof setup>,name:string,max=3){return executeProduction(x.graph,x.root,name,initialState({episodeId:name,graph:{mediaMode:'real',beats:2,maxGenerations:max,testRender:true}}));}
async function main(){
 assert.equal(takeCount(4.9),1);assert.equal(takeCount(7),2);assert.equal(takeCount(12),3);const pt=planTakes([{beatId:'B',imagePrompt:'i',videoPrompt:'v',cameraMotion:'x',durationSeconds:7,firstFrameFrom:'image'}],new Map([['B','first.png']]),base);assert.equal(pt[1].firstFrameSource,'previous-take');assert.equal(pt[1].dependsOnTake,'B-take-1');console.log('PASS 8: Kling-only take rule and explicit continuity dependency');
 const happy=setup('REAL_HAPPY',{unresolved:true});try{const s=await runNew(happy,'REAL_HAPPY');assert.deepEqual(s.next,['packaging_stage']);assert.equal(s.values.videoTakes.length,3);assert.equal(s.values.generationCount,3);assert.equal(s.values.sfxUnresolved.length,1);assert.ok(s.values.finalVideo?.outPath.includes(path.join('out','test')));console.log('PASS 1,6: real two-beat flow through mux and visible unresolved SFX');}finally{happy.saver.db.close();}
 const manual=setup('IMAGE_MANUAL');for(const b of ['SCENE_001','SCENE_002'])fs.rmSync(path.join(manual.root,'runs','IMAGE_MANUAL','images',b),{recursive:true,force:true});try{let s=await runNew(manual,'IMAGE_MANUAL');assert.equal((s.tasks[0].interrupts[0].value as any).kind,'IMAGE_MANUAL');for(const x of s.values.imageSpecs)media(x.expectedPath,true);s=await executeProduction(manual.graph,manual.root,'IMAGE_MANUAL',new Command({resume:{resumed:true}}));assert.ok(s.values.frames.length>=2);console.log('PASS 3: IMAGE_MANUAL interrupt and resume');}finally{manual.saver.db.close();}
 const recovery=setup('RECOVERY',{missingTake:2});try{let s=await runNew(recovery,'RECOVERY');assert.equal((s.tasks[0].interrupts[0].value as any).kind,'FIREFLY_RECOVERY');const t=s.values.videoTakes.find((x:any)=>x.status==='dispatched')!;media(t.outputPath,false,5);s=await executeProduction(recovery.graph,recovery.root,'RECOVERY',new Command({resume:{resumed:true}}));assert.deepEqual(s.next,['packaging_stage']);console.log('PASS 2: FIREFLY_RECOVERY interrupt and resume');}finally{recovery.saver.db.close();}
 const review=setup('REVIEW',{lowReview:true});try{const s=await runNew(review,'REVIEW');assert.equal(s.values.promptIteration,2);assert.ok(review.ideCalls>=4);console.log('PASS 4: prompt review loops once then passes');}finally{review.saver.db.close();}
 const limit=setup('LIMIT');try{await assert.rejects(runNew(limit,'LIMIT',0),/MAX_GENERATIONS_EXCEEDED/);console.log('PASS 5: maxGenerations blocks before dispatch');}finally{limit.saver.db.close();}
 const busy=setup('PROFILE_BUSY',{busy:true});try{await assert.rejects(runNew(busy,'PROFILE_BUSY'),/FIREFLY_PROFILE_IN_USE/);console.log('PASS 9: profile in use fails clearly before generation');}finally{busy.saver.db.close();}
 const login=setup('LOGIN',{sessionInvalid:true});try{let s=await runNew(login,'LOGIN');assert.equal((s.tasks[0].interrupts[0].value as any).kind,'FIREFLY_LOGIN');s=await executeProduction(login.graph,login.root,'LOGIN',new Command({resume:{resumed:true}}));assert.deepEqual(s.next,['packaging_stage']);console.log('PASS 10: invalid session login interrupt and revalidation');}finally{login.saver.db.close();}
 console.log('Evidence '+base);
}
main().catch(e=>{console.error(e);process.exitCode=1});
