import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { Command } from '@langchain/langgraph';import { createCheckpointer } from '../../checkpointer';import { createProductionGraph } from '../graph';import { initialState,type State } from '../state';import { archiveStage,pruneStorage } from '../storage/nodes';import type { StorageCandidate,StorageEntry } from '../storage/model';import { md5File } from '../storage/hash';import { migrate } from '../storage/migrate';import { remoteSubpath } from '../storage/tiers';import { fixtures } from './fixtures';import { executeProduction } from '../runner';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'hsl-storage-'));
function state(episode='EP'){const update=initialState({episodeId:episode,graph:{storageMode:'drive',prune:'dry-run',keepLocalDeliverables:0,mediaMode:'legacy'}}) as any;return{...update,storageIndex:[],errors:[],timings:[],frames:[],videos:[],videoTakes:[],renderChunks:[],productionStatus:'COMPLETED'} as State;}
function write(rel:string,text='x'){const file=path.join(root,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);return file;}
async function entry(rel:string,tier:StorageEntry['tier'],status:StorageEntry['status']='both'){const file=write(rel,rel),md5=await md5File(file);return{path:rel.replace(/\\/g,'/'),tier,sizeBytes:fs.statSync(file).size,md5,remoteMd5:status==='both'?md5:undefined,status} as StorageEntry;}
async function main(){process.env.HSL_DRIVE_FOLDER_ID='folder';process.env.HSL_GOOGLE_CLIENT_SECRET_FILE=path.join(root,'secret.json');
  assert.notEqual(remoteSubpath({tier:'intermediate',path:path.join(root,'runs','EP','a','prompt.md')},'EP','migration',root),remoteSubpath({tier:'intermediate',path:path.join(root,'runs','EP','b','prompt.md')},'EP','migration',root));
  const three=[write('runs/EP/images/a.png'),write('runs/EP/images/b.png'),write('runs/EP/images/c.png')];const candidates=three.map(p=>({path:p,tier:'intermediate',category:'images'} as StorageCandidate));
  const archive=archiveStage('test',()=>candidates)({root,deps:{driveUploadVerified:async(manifest:string)=>{const items=JSON.parse(fs.readFileSync(manifest,'utf8')).items;return{items:[{localPath:items[0].localPath,driveFileId:'1',remoteMd5:items[0].md5,status:'uploaded'},{localPath:items[1].localPath,driveFileId:'2',remoteMd5:items[1].md5,status:'already'},{localPath:items[2].localPath,driveFileId:'3',remoteMd5:'bad',status:'mismatch'}]};}} as any});
  const archived=await archive(state(),{} as any) as any;assert.deepEqual(archived.storageIndex.map((x:StorageEntry)=>x.status),['both','both','mismatch']);console.log('PASS 16: uploaded/already/mismatch indexed; mismatch not verified');
  const network=archiveStage('network',()=>[candidates[0]])({root,deps:{driveUploadVerified:async()=>{throw new Error('network');}} as any});const failed=await network(state(),{} as any) as any;assert.equal(failed.storageIndex[0].status,'pending-upload');assert.ok(failed.errors.length);console.log('PASS 17: upload failure is pending and non-blocking');
  const verified=await entry('runs/EP/images/verified.png','intermediate'),mismatch=await entry('runs/EP/images/mismatch.png','intermediate','mismatch'),transient=await entry('out/temp_EP.mp4','transient','local');let s=state();s.storageIndex=[verified,mismatch,transient];let pruned=await pruneStorage(root,s,false);assert.ok(fs.existsSync(path.join(root,verified.path)));assert.ok(fs.existsSync(pruned.planFile));pruned=await pruneStorage(root,{...s,options:{...s.options,graph:{...s.options.graph,prune:'apply'}}},true);assert.ok(!fs.existsSync(path.join(root,verified.path)));assert.ok(!fs.existsSync(path.join(root,transient.path)));assert.ok(fs.existsSync(path.join(root,mismatch.path)));console.log('PASS 18: dry-run preserves; apply deletes verified and transient only');
  const current=await entry('deliveries/EP/video/current.mp4','deliverable'),old=await entry('deliveries/OLD/video/old.mp4','deliverable');const keep=state();keep.options.graph.keepLocalDeliverables=1;keep.storageIndex=[current,old];await pruneStorage(root,keep,true);assert.ok(fs.existsSync(path.join(root,current.path)));assert.ok(!fs.existsSync(path.join(root,old.path)));console.log('PASS 19: current deliverable retained, older verified deleted');
  const save=await entry('runs/EP/scene-plan.json','save');const saveState=state();saveState.storageIndex=[save];await pruneStorage(root,saveState,true);assert.ok(fs.existsSync(path.join(root,save.path)));console.log('PASS 20: save is never deleted');
  const outside=write('../outside-storage-test.txt');const confined=state();confined.storageIndex=[{path:'../outside-storage-test.txt',tier:'intermediate',sizeBytes:1,md5:await md5File(outside),remoteMd5:await md5File(outside),status:'both'}];const confinement=await pruneStorage(root,confined,true);assert.ok(fs.existsSync(outside));assert.match(confinement.errors[0],/PATH_CONFINEMENT/);console.log('PASS 21: outside path refused');
  const graphRoot=path.join(root,'graph');fs.mkdirSync(graphRoot,{recursive:true});const mock=fixtures(graphRoot,'AUTH');let checks=0,spawns=0;const saver=createCheckpointer(graphRoot),graph=createProductionGraph(saver,{...mock.deps,driveCheckAuth:async()=>({exitCode:++checks===1?2:0,stdout:'',stderr:'',timedOut:false,durationMs:1}),driveUploadVerified:async(manifest:string)=>{spawns++;const items=JSON.parse(fs.readFileSync(manifest,'utf8')).items;return{items:items.map((x:any)=>({localPath:x.localPath,driveFileId:'id',remoteMd5:x.md5,status:'already'}))};}} as any,graphRoot);let snap=await executeProduction(graph,graphRoot,'AUTH',initialState({episodeId:'AUTH',graph:{storageMode:'drive',mediaMode:'legacy'}}));assert.equal((snap.tasks[0].interrupts[0].value as any).kind,'DRIVE_AUTH');snap=await executeProduction(graph,graphRoot,'AUTH',new Command({resume:{resumed:true}}));assert.equal(snap.values.productionStatus,'COMPLETED');assert.ok(spawns>0);saver.db.close();console.log('PASS 22: DRIVE_AUTH interrupt revalidates on resume');
  const offRoot=path.join(root,'off');fs.mkdirSync(offRoot,{recursive:true});const offMock=fixtures(offRoot,'OFF'),offSaver=createCheckpointer(offRoot);let driveCalls=0;const offGraph=createProductionGraph(offSaver,{...offMock.deps,driveCheckAuth:async()=>{driveCalls++;throw new Error('should not spawn');},driveUploadVerified:async()=>{driveCalls++;throw new Error('should not spawn');}} as any,offRoot);const offSnap=await executeProduction(offGraph,offRoot,'OFF',initialState({episodeId:'OFF',graph:{storageMode:'off',mediaMode:'legacy'}}));assert.equal(offSnap.values.productionStatus,'COMPLETED');assert.equal(driveCalls,0);assert.ok(offSnap.values.storageIndex.length);offSaver.db.close();console.log('PASS 23: storage off indexes locally with zero Python calls');
  const migrationRoot=path.join(root,'migration');writeAt(migrationRoot,'runs/E/scene-plan.json');writeAt(migrationRoot,'runs/E/images/B/B.png');writeAt(migrationRoot,'deliveries/E/video/final.mp4');writeAt(migrationRoot,'out/temp_E.mp4');writeAt(migrationRoot,'public/runs/E/frame.png');await migrate(['--scan','--root',migrationRoot]);const report=JSON.parse(fs.readFileSync(path.join(migrationRoot,'runs','storage-migration.json'),'utf8'));assert.equal(report.items.length,5);await migrate(['--prune','--root',migrationRoot]);assert.ok(report.items.every((x:any)=>fs.existsSync(path.join(migrationRoot,x.path))));console.log('PASS 24: five-file scan totals and prune dry-run preserve files');
  console.log('Evidence '+root);
}
function writeAt(base:string,rel:string){const f=path.join(base,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,rel);}
main().catch(e=>{console.error(e);process.exitCode=1;});
