%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	scene_plan(scene_plan)
	env_check(env_check)
	codex_auth_prepare(codex_auth_prepare)
	codex_auth_wait(codex_auth_wait)
	drive_auth_wait(drive_auth_wait)
	archive_scene_plan(archive_scene_plan)
	visual_prompts_prepare(visual_prompts_prepare)
	visual_prompts_wait(visual_prompts_wait)
	visual_prompts_review_prepare(visual_prompts_review_prepare)
	visual_prompts_review_wait(visual_prompts_review_wait)
	image_generate_prepare(image_generate_prepare)
	image_generate_run(image_generate_run)
	image_generate_wait(image_generate_wait)
	image_review_prepare(image_review_prepare)
	image_review_wait(image_review_wait)
	archive_images(archive_images)
	fan_out_frames(fan_out_frames)
	image_frames(image_frames)
	join_frames(join_frames)
	firefly_session_prepare(firefly_session_prepare)
	firefly_session_wait(firefly_session_wait)
	firefly_guide(firefly_guide)
	firefly_dispatch(firefly_dispatch)
	firefly_intake_wait(firefly_intake_wait)
	archive_firefly(archive_firefly)
	firefly_finalize(firefly_finalize)
	fan_out_videos(fan_out_videos)
	firefly_videos(firefly_videos)
	join_videos(join_videos)
	narration_stage(narration_stage)
	sound_design(sound_design)
	sfx_render(sfx_render)
	archive_audio(archive_audio)
	gatekeeper_stage(gatekeeper_stage)
	gate_render_wait(gate_render_wait)
	render_prepare(render_prepare)
	fan_out_render(fan_out_render)
	render_chunk(render_chunk)
	stitch(stitch)
	pre_mux_gate(pre_mux_gate)
	mux(mux)
	packaging_stage(packaging_stage)
	compliance_stage(compliance_stage)
	archive_compliance(archive_compliance)
	gate_publish_wait(gate_publish_wait)
	finalize(finalize)
	prune_verified(prune_verified)
	__end__([<p>__end__</p>]):::last
	__start__ --> scene_plan;
	archive_audio --> gatekeeper_stage;
	archive_compliance --> prune_verified;
	archive_images --> join_frames;
	codex_auth_prepare --> codex_auth_wait;
	drive_auth_wait --> archive_scene_plan;
	env_check --> codex_auth_prepare;
	fan_out_frames --> image_frames;
	fan_out_videos --> firefly_videos;
	finalize --> archive_compliance;
	firefly_dispatch --> firefly_intake_wait;
	firefly_finalize --> join_videos;
	firefly_intake_wait --> archive_firefly;
	firefly_session_prepare --> firefly_session_wait;
	firefly_videos --> join_videos;
	gate_publish_wait --> finalize;
	image_frames --> join_frames;
	image_generate_prepare --> image_generate_run;
	image_generate_run --> image_generate_wait;
	image_review_prepare --> image_review_wait;
	join_videos --> narration_stage;
	mux --> packaging_stage;
	narration_stage --> sound_design;
	packaging_stage --> compliance_stage;
	pre_mux_gate --> mux;
	prune_verified --> __end__;
	render_chunk --> fan_out_render;
	render_prepare --> fan_out_render;
	scene_plan --> env_check;
	sfx_render --> archive_audio;
	sound_design --> sfx_render;
	stitch --> pre_mux_gate;
	visual_prompts_prepare --> visual_prompts_wait;
	visual_prompts_review_prepare --> visual_prompts_review_wait;
	visual_prompts_wait --> visual_prompts_review_prepare;
	codex_auth_wait -.-> drive_auth_wait;
	codex_auth_wait -.-> codex_auth_prepare;
	archive_scene_plan -.-> fan_out_frames;
	archive_scene_plan -.-> visual_prompts_prepare;
	visual_prompts_review_wait -.-> visual_prompts_prepare;
	visual_prompts_review_wait -.-> image_generate_prepare;
	image_generate_wait -.-> image_generate_run;
	image_generate_wait -.-> image_review_prepare;
	image_review_wait -.-> image_generate_run;
	image_review_wait -.-> archive_images;
	join_frames -.-> fan_out_videos;
	join_frames -.-> firefly_session_prepare;
	firefly_session_wait -.-> firefly_guide;
	firefly_session_wait -.-> firefly_session_prepare;
	firefly_guide -.-> firefly_dispatch;
	firefly_guide -.-> finalize;
	archive_firefly -.-> firefly_dispatch;
	archive_firefly -.-> firefly_finalize;
	gatekeeper_stage -.-> gate_render_wait;
	gatekeeper_stage -.-> finalize;
	gate_render_wait -.-> finalize;
	gate_render_wait -.-> render_prepare;
	fan_out_render -.-> render_chunk;
	fan_out_render -.-> stitch;
	compliance_stage -.-> gate_publish_wait;
	compliance_stage -.-> finalize;
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;

