import 'dotenv/config';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {REPO_ROOT} from '../checkpointer';
import {spawnTool,requireSuccess} from '../lib/proc';
import {agentGuide,detailedProbe,fireflyEnvironment,probeSession,profileInUse,reconcileUnstartedAgentTake,runAgentTake} from './lib/firefly';
import type {VideoTake,VisualPrompt} from './state';

const healthRoot=path.join(REPO_ROOT,'runs','kling-health');
const day=new Date().toISOString().slice(0,10).replace(/-/g,'');
const runtime=path.join(healthRoot,`KLING_HEALTH_${day}`);
const reportPath=path.join(runtime,'health-report.json');
const checkReportPath=path.join(runtime,'check-report.json');
const hash=(file:string)=>{const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),buf=Buffer.alloc(1024*1024);try{for(;;){const n=fs.readSync(fd,buf,0,buf.length,null);if(!n)break;h.update(buf.subarray(0,n));}}finally{fs.closeSync(fd);}return h.digest('hex');};
const write=(file:string,value:unknown)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n');};
function firstFrame(){const candidates=[path.join(REPO_ROOT,'runs','HSL_EPISODE_011','frames','SCENE_001.png'),path.join(REPO_ROOT,'runs','HSL_EPISODE_011','images','SCENE_001','SCENE_001.png')];const found=candidates.find(fs.existsSync);if(!found)throw new Error(`KLING_HEALTH_FRAME_MISSING:${candidates.join('|')}`);return found;}
async function motionCheck(video:string){const dir=path.join(runtime,'qa-frames'),first=path.join(dir,'first.png'),last=path.join(dir,'last.png');fs.mkdirSync(dir,{recursive:true});requireSuccess(await spawnTool('ffmpeg',['-y','-hide_banner','-loglevel','error','-i',video,'-frames:v','1',first],{cwd:runtime,timeoutMs:60_000}),'KLING_QA_FIRST_FRAME');requireSuccess(await spawnTool('ffmpeg',['-y','-hide_banner','-loglevel','error','-sseof','-0.1','-i',video,'-frames:v','1',last],{cwd:runtime,timeoutMs:60_000}),'KLING_QA_LAST_FRAME');return{first,last,framesDiffer:hash(first)!==hash(last)};}
async function technicalQa(video:string){const probe=await detailedProbe(video),sizeBytes=fs.statSync(video).size,motion=await motionCheck(video);const checks={codec:probe.codec==='h264',resolution:probe.width===1920&&probe.height===1080,aspectRatio:Boolean(probe.width&&probe.height&&Math.abs(probe.width/probe.height-16/9)<0.02),duration:probe.duration>=4.5,fps:Boolean(probe.fps&&probe.fps>=23&&probe.fps<=60),fileSize:sizeBytes>=100_000,motion:motion.framesDiffer};return{status:Object.values(checks).every(Boolean)?'PASS':'FAIL',model:'Kling 2.5 Turbo',probe,sizeBytes,sha256:hash(video),checks,motion};}
async function check(){const environment=fireflyEnvironment(),busy=await profileInUse(environment.profileDir);if(busy)throw new Error(`KLING_PROFILE_IN_USE:${environment.profileDir}`);const session=await probeSession(environment,path.join(runtime,'session-check'),path.join(runtime,'session-check.log'));const candidates=[path.join(runtime,'saida','KLING_HEALTH-take-1.mp4'),path.join(REPO_ROOT,'runs','phase2-discovery','kling25-canary','runtime','saida','HSL_PHASE2_KLING25_CLEAN_PROFILE.mp4')],existing=candidates.find(fs.existsSync);const prior=existing?await technicalQa(existing):null;const result={schema:'hsl.kling-health.v1',checkedAt:new Date().toISOString(),sessionAuthenticated:session,profileAvailable:!busy,canarySource:existing??null,priorCanary:prior};write(checkReportPath,result);console.log(JSON.stringify(result,null,2));if(!session||prior?.status==='FAIL')process.exitCode=2;}
async function live(){if(process.env.HSL_ALLOW_PAID_FIREFLY_DISPATCH!=='true')throw new Error('Defina HSL_ALLOW_PAID_FIREFLY_DISPATCH=true para autorizar exatamente este canário.');const environment=fireflyEnvironment();if(await profileInUse(environment.profileDir))throw new Error(`KLING_PROFILE_IN_USE:${environment.profileDir}`);if(!await probeSession(environment,path.join(runtime,'session-check'),path.join(runtime,'session-check.log')))throw new Error('KLING_SESSION_NOT_AUTHENTICATED');const frame=firstFrame(),output=path.join(runtime,'saida','KLING_HEALTH-take-1.mp4');const prompt:VisualPrompt={beatId:'KLING_HEALTH',imagePrompt:'health canary',videoPrompt:'Slow controlled cinematic camera push through the industrial environment. Preserve the exact subject, composition, physical geometry, lighting, and documentary realism of the first frame. No text, no logos, no new people.',cameraMotion:'slow controlled push',durationSeconds:5,firstFrameFrom:'image'};const take:VideoTake={beatId:'KLING_HEALTH',takeIndex:1,requestedSeconds:5,firstFrameSource:'image',firstFramePath:frame,outputPath:output,status:'pending'};const guidePath=path.join(runtime,'guide.json');write(guidePath,agentGuide(prompt,take));await runAgentTake(environment,runtime,guidePath,path.join(runtime,'dispatch.log'));const qa=await technicalQa(output);const result={schema:'hsl.kling-health.v1',checkedAt:new Date().toISOString(),kind:'paid-canary',generationLimit:1,...qa,video:output};write(reportPath,result);console.log(JSON.stringify(result,null,2));if(qa.status!=='PASS')process.exitCode=2;}
async function reconcile(){const takeRuntime=process.argv[3],guidePath=process.argv[4];if(!takeRuntime||!guidePath)throw new Error('Uso: klingSupervisor.ts reconcile <runtime> <guide.json>');const result=await reconcileUnstartedAgentTake(fireflyEnvironment(),path.resolve(takeRuntime),path.resolve(guidePath),path.join(path.resolve(takeRuntime),'reconcile.log'));console.log(JSON.stringify({status:'REQUEUED_UNSTARTED_INFRA',runtime:path.resolve(takeRuntime),exitCode:result.exitCode},null,2));}

const command=process.argv[2]??'check';(command==='check'?check():command==='live'?live():command==='reconcile'?reconcile():Promise.reject(new Error('Uso: klingSupervisor.ts check|live|reconcile <runtime> <guide.json>'))).catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1;});
