// Generated by HSL Sound Design Agent - AudioPlan v1.0.0
// Video ID: video_sample_dark_comedy_01 | Total Frames: 540 | FPS: 30
import React from 'react';
import {Audio, Sequence, staticFile, interpolate} from 'remotion';

function dbToLinear(db: number): number {
  return Math.pow(10, db / 20);
}

export const RemotionCinematicAudioBed: React.FC = () => {
  return (
    <>
      {/* ======================================================== */}
      {/* SCENE: scene_01 (suspense | office_night) */}
      {/* ======================================================== */}
      <Sequence from={0} durationInFrames={180}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={180}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_01.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | foley_keyboard | mid) */} 
        <Sequence from={36} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_02.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (creative | riser | high) */} 
        <Sequence from={110} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (impact | ominous_boom | low) */} 
        <Sequence from={180} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_01.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_001 (triple_calcar) */}
        <Sequence from={165} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={170} durationInFrames={10}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_02.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={180} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_01.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_02 (emotional | contemplative_room) */}
      {/* ======================================================== */}
      <Sequence from={180} durationInFrames={180}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/emotional/emotional_heartbreaking.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={180}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_03.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (foley | foley_paper | mid) */} 
        <Sequence from={60} durationInFrames={60}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_04.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (whoosh | whoosh | high) */} 
        <Sequence from={140} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* Transition: trans_002 (triple_calcar) */}
        <Sequence from={165} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_02.wav')} volume={dbToLinear(-28)} />
        </Sequence>
        <Sequence from={170} durationInFrames={10}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_03.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={180} durationInFrames={15}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_02.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_03 (epic | monumental_exterior) */}
      {/* ======================================================== */}
      <Sequence from={360} durationInFrames={180}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-24);
          }}
        />
        {/* SFX Layer: layer_001 (ambience | room_tone | mid) */} 
        <Sequence from={0} durationInFrames={180}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_05.wav')}
            volume={0.0251}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (impact | ominous_boom | low) */} 
        <Sequence from={120} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_02.wav')}
            volume={0.1995}
          />
        </Sequence>
      </Sequence>

    </>
  );
};
