// Generated by HSL Sound Design Agent - AudioPlan v1.0.0
// Video ID: video_sample_dark_comedy_01 | Total Frames: 540 | FPS: 30
import React from 'react';
import {Audio, Sequence, staticFile, interpolate} from 'remotion';

function dbToLinear(db: number): number {
  return Math.pow(10, db / 20);
}

export const RemotionCinematicAudioBed: React.FC = () => {
  return (
    <>
      {/* ======================================================== */}
      {/* SCENE: scene_01 (suspense | office_night) */}
      {/* ======================================================== */}
      <Sequence from={0} durationInFrames={180}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/suspense/suspense_unseen_horrors.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={90}>
          <Audio
            src={staticFile('audio/sfx/cinematic/braams/braam_hit_02.wav')}
            volume={0.1778}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={180}>
          <Audio
            src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_02.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/ui/ui_click_01.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/ui/ui_click_64.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_32.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (foley | foley_keyboard | mid) */} 
        <Sequence from={36} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_11.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_007 (riser | riser | high) */} 
        <Sequence from={110} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/tension/tension_riser_01.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_008 (impact | ominous_boom | low) */} 
        <Sequence from={180} durationInFrames={50}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_05.wav')}
            volume={0.1995}
          />
        </Sequence>
        {/* Transition: trans_001 (triple_calcar) */}
        <Sequence from={160} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_05.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={155} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_05.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={180} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_74.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_02 (emotional | contemplative_room) */}
      {/* ======================================================== */}
      <Sequence from={180} durationInFrames={180}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/emotional/emotional_heartbreaking.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_35.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={180}>
          <Audio
            src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_01.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/ui/ui_click_17.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/ui/ui_click_65.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_61.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (foley | foley_paper | mid) */} 
        <Sequence from={60} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/foley/household/foley_household_09.wav')}
            volume={0.0794}
          />
        </Sequence>
        {/* SFX Layer: layer_007 (whoosh | whoosh | high) */} 
        <Sequence from={140} durationInFrames={30}>
          <Audio
            src={staticFile('audio/sfx/cinematic/whooshes/whoosh_swoosh_03.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* Transition: trans_002 (triple_calcar) */}
        <Sequence from={160} durationInFrames={30}>
          <Audio src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_04.wav')} volume={dbToLinear(-26)} />
        </Sequence>
        <Sequence from={155} durationInFrames={25}>
          <Audio src={staticFile('audio/sfx/cinematic/tension/tension_riser_03.wav')} volume={dbToLinear(-18)} />
        </Sequence>
        <Sequence from={180} durationInFrames={20}>
          <Audio src={staticFile('audio/sfx/cinematic/impacts/impact_strike_58.wav')} volume={dbToLinear(-16)} />
        </Sequence>
      </Sequence>

      {/* ======================================================== */}
      {/* SCENE: scene_03 (epic | monumental_exterior) */}
      {/* ======================================================== */}
      <Sequence from={360} durationInFrames={180}>
        {/* Music: tension_bed */} 
        <Audio
          src={staticFile('audio/music/cinematic/epic/epic_impact_moderato.mp3')}
          volume={(f) => {
            // Dynamic Ducking during voice presence
            return dbToLinear(-26);
          }}
        />
        {/* SFX Layer: layer_001 (impact | scene_entrance_punch | low) */} 
        <Sequence from={0} durationInFrames={45}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_04.wav')}
            volume={0.1413}
          />
        </Sequence>
        {/* SFX Layer: layer_002 (drone | tension_drone_bed | mid) */} 
        <Sequence from={0} durationInFrames={180}>
          <Audio
            src={staticFile('audio/sfx/cinematic/loops/loop_atmosphere_03.wav')}
            volume={0.0398}
          />
        </Sequence>
        {/* SFX Layer: layer_003 (foley | ui_text_eyebrow_reveal | high) */} 
        <Sequence from={8} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/ui/ui_click_78.wav')}
            volume={0.1000}
          />
        </Sequence>
        {/* SFX Layer: layer_004 (foley | ui_accent_line_expand | high) */} 
        <Sequence from={18} durationInFrames={12}>
          <Audio
            src={staticFile('audio/sfx/ui/ui_click_72.wav')}
            volume={0.0891}
          />
        </Sequence>
        {/* SFX Layer: layer_005 (impact | ui_headline_pop_hit | mid) */} 
        <Sequence from={30} durationInFrames={25}>
          <Audio
            src={staticFile('audio/sfx/cinematic/impacts/impact_strike_80.wav')}
            volume={0.1259}
          />
        </Sequence>
        {/* SFX Layer: layer_006 (impact | ominous_boom | low) */} 
        <Sequence from={120} durationInFrames={50}>
          <Audio
            src={staticFile('audio/sfx/cinematic/booms/boom_explosion_03.wav')}
            volume={0.1995}
          />
        </Sequence>
      </Sequence>

    </>
  );
};
